### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by fredericob** [fredericob/northstar#17]
- [ ] Create Static page layout including Header and Footer

### Create pages & subpages ###
- [ ] About
  - [ ] Meet the Head
  - [ ] Curriculum
  - [ ] Mission
  - [ ] Ethos
- [ ] School Info
  - [ ] Admissions
  - [ ] Policies
  - [ ] Staff and Governors
  - [ ] Vacancies
  - [ ] Ofsted Reports
- [ ] Parents and Carers
  - [ ] Term Dates
  - [ ] Lunch Menus
  - [ ] Pupils Activities
       - [ ] Learning Activities
       - [ ] Trips
       - [ ] Events
- [ ] News & Events
   - [ ] News
   - [ ] Events
   - [ ] Social Feed
   - [ ] Blog
      - [ ] Categories
   - [ ] Newsletters
- [ ] Contact
  - [ ] Contact
  - [ ] Complaints
- [ ] Error
  - [ ] 404
  - [ ] 500
